name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Setup Git LFS
        run: git lfs install

      - name: Fetch all LFS objects
        run: git lfs fetch --all

      - name: Pull LFS objects
        run: git lfs pull

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://huggingface.co/spaces/KaggleGPT/KaggleGPT main
