name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false

      - name: Remove research folder
        run: rm -rf research/
      
      - name: Git config added 1
        run: git config --global user.email "rahulbhoyaroffice@gmail.com"

      - name: Git config added 2
        run: git config --global user.name "Rahul Bhoyar"

      - name: Commit changes
        run: |
            git add -A
            git commit -m "Remove research folder before push" || echo "No changes to commit"
  
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://rahul-bhoyar-1995:$HF_TOKEN@huggingface.co/spaces/KaggleGPT/KaggleGPT main